server:
  port: 8761
eureka:
  instance:
    hostname: eureka-server
  client:
    # Sobrescreve a configuração global e evita que o Eureka tente se registrar nele mesmo
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0