jenkins:
  systemMessage: "SafeRoute CI — Configured as Code"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "${JENKINS_ADMIN_ID}"
          password: "${JENKINS_ADMIN_PASSWORD}"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false

unclassified:
  location:
    url: "http://localhost:8090/"

jobs:
  - script: >
      pipelineJob('saferoute-pipeline') {
        description('SafeRoute CI/CD Pipeline')
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('${REPO_URL}')
                }
                branch('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }
